import type {
  PlumbingPriceMappingItem,
  PlumbingQuantityField,
  PlumbingWorkKind,
} from '../shared/estimate.types'

export const PLUMBING_SECTION_ID = 'plumbing'
export const PLUMBING_SECTION_TITLE = 'Сантехника (labour)'

/**
 * Whitelist labour-работ по сантехнике для внутреннего калькулятора.
 * Primary: PDF `anfas-price-list.pdf`. Frontend — сверка при `source=both`.
 * Вне scope: материалы (трубы, приборы как товар), отопление (радиаторы/котлы/конвекторы),
 * штробы дм³, заполнение штроб, выезд 15k, звукоизоляция стояка, электро-полотенцесушитель,
 * конструкции ТЕСЕ (отложено), мебель санузла.
 */

type Kind = PlumbingWorkKind
type From = PlumbingQuantityField

/** PDF-only labour позиция (без сверки с публичным прайсом). */
function pdf(
  id: string,
  title: string,
  unit: string,
  unitPrice: number,
  kind: Kind,
  from: From,
): PlumbingPriceMappingItem {
  return {
    id,
    title,
    unit,
    unitPrice,
    source: 'pdf',
    kind,
    defaultEnabled: false,
    defaultQuantityFrom: from,
  }
}

/** Позиция, сверяемая с публичным прайсом (`santehmontazh` / `demontazh`). */
function both(
  id: string,
  title: string,
  unit: string,
  unitPrice: number,
  kind: Kind,
  from: From,
  frontendCategorySlug: 'santehmontazh' | 'demontazh',
  frontendName?: string,
): PlumbingPriceMappingItem {
  return {
    id,
    title,
    unit,
    unitPrice,
    source: 'both',
    kind,
    frontendCategorySlug,
    frontendName: frontendName ?? title,
    frontendUnitPrice: unitPrice,
    defaultEnabled: false,
    defaultQuantityFrom: from,
  }
}

export const PLUMBING_PRICE_MAPPING: readonly PlumbingPriceMappingItem[] = [
  // —— Демонтаж ——
  both('demolition-toilet', 'Демонтаж унитаза', 'шт.', 1800, 'demolition', 'plumbingToiletsCount', 'demontazh'),
  pdf('demolition-sink', 'Демонтаж раковины', 'шт.', 1500, 'demolition', 'plumbingSinksCount'),
  both('demolition-bath', 'Демонтаж ванны', 'шт.', 3500, 'demolition', 'plumbingBathtubsCount', 'demontazh'),
  pdf('demolition-mixer', 'Демонтаж смесителей', 'шт.', 900, 'demolition', 'plumbingMixersCount'),

  // —— Канализация ——
  pdf('drainage-layout', 'Разметка трассы канализации перед сантехмонтажными работами', 'м. пог.', 250, 'drainage', 'plumbingSewerPipeLength'),
  both(
    'drainage-pipe-d32-50',
    'Монтаж канализационной трубы d32–50',
    'м. пог.',
    450,
    'drainage',
    'plumbingSewerPipeLength',
    'santehmontazh',
  ),
  pdf('drainage-pipe-d75', 'Монтаж канализационной трубы d75', 'м. пог.', 550, 'drainage', 'plumbingSewerPipeLength'),
  both(
    'drainage-pipe-d110',
    'Монтаж канализационной трубы d110',
    'м. пог.',
    650,
    'drainage',
    'plumbingSewerPipeLength',
    'santehmontazh',
  ),
  pdf('drainage-pipe-d160', 'Монтаж канализационной трубы d160', 'м. пог.', 850, 'drainage', 'plumbingSewerPipeLength'),
  pdf('drainage-elbow-d32-50', 'Монтаж канализационного отвода/поворота d32–50', 'шт.', 700, 'drainage', 'plumbingSewerPointsCount'),
  pdf('drainage-elbow-d110', 'Монтаж канализационного отвода/поворота d110', 'шт.', 1000, 'drainage', 'plumbingSewerPointsCount'),
  pdf('drainage-tee-d32-50', 'Монтаж канализационного тройника d32–50', 'шт.', 1000, 'drainage', 'plumbingSewerPointsCount'),
  pdf('drainage-tee-d110', 'Монтаж канализационного тройника d110', 'шт.', 1500, 'drainage', 'plumbingSewerPointsCount'),
  pdf('drainage-revision', 'Монтаж канализационной ревизии', 'шт.', 1500, 'drainage', 'manual'),
  pdf('drainage-outlet-fix', 'Фиксация вывода канализации в проектное положение d32–110', 'шт.', 2500, 'drainage', 'plumbingSewerPointsCount'),
  pdf('drainage-slope', 'Выставление уклона канализационной трассы', 'м. пог.', 400, 'drainage', 'plumbingSewerPipeLength'),
  pdf('drainage-clamp', 'Крепление канализационной трубы к основанию/стене', 'шт.', 350, 'drainage', 'manual'),
  pdf('drainage-seal-pass', 'Герметизация прохода канализационной трубы через конструкцию', 'шт.', 1000, 'drainage', 'manual'),
  pdf('drainage-test-flush', 'Пробная проливка канализации после монтажа', 'комплекс', 2500, 'drainage', 'manual'),
  pdf('drainage-riser-d50', 'Замена стояка канализации d50', 'шт.', 10000, 'drainage', 'manual'),
  pdf('drainage-riser-d110', 'Замена стояка канализации d110', 'шт.', 15000, 'drainage', 'manual'),
  pdf('drainage-riser-reconfig', 'Изменение конфигурации стояка канализации', 'шт.', 6000, 'drainage', 'manual'),
  pdf('drainage-riser-insert-steel', 'Врезка в стояк из стали', 'шт.', 5500, 'drainage', 'manual'),
  pdf('drainage-riser-insert-pp', 'Врезка в стояк из полипропилена', 'шт.', 3500, 'drainage', 'manual'),
  pdf('drainage-riser-console', 'Монтаж консолей Walraven', 'шт.', 900, 'drainage', 'manual'),
  pdf('drainage-riser-clamp', 'Монтаж хомута крепления стояка', 'шт.', 700, 'drainage', 'manual'),
  pdf('drainage-riser-relocate', 'Перенос отвода стояка', 'шт.', 4500, 'drainage', 'manual'),
  pdf('drainage-riser-fire-collar', 'Монтаж противопожарной манжеты на стояк', 'шт.', 1800, 'drainage', 'manual'),

  // —— Водоснабжение ——
  pdf('water-layout', 'Разметка трассы водоснабжения перед сантехмонтажными работами', 'м. пог.', 250, 'water-supply', 'plumbingWaterPipeLength'),
  both(
    'water-pipe-d16-20',
    'Прокладка водопроводной трубы d16–20',
    'м. пог.',
    450,
    'water-supply',
    'plumbingWaterPipeLength',
    'santehmontazh',
  ),
  pdf('water-pipe-d25-32', 'Прокладка водопроводной трубы d25–32', 'м. пог.', 550, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-pipe-d40-63', 'Прокладка водопроводной трубы d40–63', 'м. пог.', 750, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-pipe-ceiling', 'Прокладка труб водоснабжения под потолком', 'м. пог.', 700, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-pipe-copper', 'Прокладка медной трубы водоснабжения', 'м. пог.', 650, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-pipe-stainless', 'Прокладка трубы из нержавеющей стали', 'м. пог.', 650, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-pipe-pp', 'Прокладка полипропиленовой трубы d20–25', 'м. пог.', 450, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-pipe-mp', 'Прокладка металлопластиковой трубы d16–20', 'м. пог.', 450, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-outlet', 'Монтаж водорозетки в проектное положение', 'шт.', 1500, 'water-supply', 'plumbingWaterPointsCount'),
  pdf('water-outlet-fix', 'Фиксация водорозетки в проектное положение', 'шт.', 1200, 'water-supply', 'plumbingWaterPointsCount'),
  pdf('water-outlet-double', 'Монтаж сдвоенной водорозетки в проектное положение', 'комплекс', 3000, 'water-supply', 'plumbingWaterPointsCount'),
  pdf('water-cap', 'Монтаж заглушки на трубопроводе', 'шт.', 500, 'water-supply', 'manual'),
  pdf('water-insulation-d16-32', 'Монтаж теплоизоляции трубы d16–32', 'м. пог.', 300, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-insulation-d40-110', 'Монтаж теплоизоляции трубы d40–110', 'м. пог.', 450, 'water-supply', 'plumbingWaterPipeLength'),
  pdf('water-riser-replace', 'Замена стояка водоснабжения', 'шт.', 15000, 'water-supply', 'manual'),

  // —— Соединения / опрессовка ——
  pdf('conn-press-d16-26', 'Радиальная/аксиальная запрессовка соединения труб d16–26', 'шт.', 700, 'connections', 'manual'),
  pdf('conn-press-d32-50', 'Радиальная/аксиальная запрессовка соединения труб d32–50', 'шт.', 1000, 'connections', 'manual'),
  pdf('conn-thread', 'Резьбовое соединение труб водоснабжения', 'шт.', 800, 'connections', 'manual'),
  pdf('conn-weld-pp-d16-20', 'Сварка полипропиленового соединения d16–20', 'шт.', 600, 'connections', 'manual'),
  pdf('conn-weld-pp-d25-32', 'Сварка полипропиленового соединения d25–32', 'шт.', 800, 'connections', 'manual'),
  pdf('conn-weld-pp-d40-63', 'Сварка полипропиленового соединения d40–63', 'шт.', 1200, 'connections', 'manual'),
  pdf('conn-electrofusion', 'Электромуфтовая сварка муфты ПНД до 90 мм за 2 стыка', 'шт.', 2500, 'connections', 'manual'),
  pdf('conn-thread-cut-30', 'Нарезка резьбы на металлической трубе до 30 мм', 'шт.', 1200, 'connections', 'manual'),
  pdf('conn-thread-cut-50', 'Нарезка резьбы на металлической трубе до 50 мм', 'шт.', 1800, 'connections', 'manual'),
  both(
    'conn-opress-water',
    'Опрессовка системы водоснабжения',
    'комплекс',
    3500,
    'connections',
    'manual',
    'santehmontazh',
  ),
  pdf('conn-flush', 'Промывка трубопровода после монтажа', 'комплекс', 2500, 'connections', 'manual'),

  // —— Водяной тёплый пол ——
  pdf('ufh-layout', 'Разметка контуров водяного тёплого пола', 'м²', 250, 'underfloor', 'plumbingWarmFloorArea'),
  pdf('ufh-insulation', 'Монтаж утеплителя для водяного тёплого пола', 'м²', 300, 'underfloor', 'plumbingWarmFloorArea'),
  pdf('ufh-foil', 'Монтаж разметочной фольги для водяного тёплого пола', 'м²', 200, 'underfloor', 'plumbingWarmFloorArea'),
  pdf('ufh-carpet', 'Монтаж разметочного ковра для водяного тёплого пола', 'м²', 350, 'underfloor', 'plumbingWarmFloorArea'),
  pdf('ufh-mesh', 'Монтаж армирующей сетки под водяной тёплый пол', 'м²', 350, 'underfloor', 'plumbingWarmFloorArea'),
  both(
    'ufh-pipe-100',
    'Монтаж трубы водяного тёплого пола шаг 100 мм',
    'м²',
    1200,
    'underfloor',
    'plumbingWarmFloorArea',
    'santehmontazh',
    'Монтаж трубы водяного тёплого пола, шаг 100 мм',
  ),
  pdf('ufh-pipe-150-200', 'Монтаж трубы водяного тёплого пола шаг 150–200 мм', 'м²', 950, 'underfloor', 'plumbingWarmFloorArea'),
  pdf('ufh-pipe-fix', 'Крепление трубы водяного тёплого пола к основанию', 'м²', 250, 'underfloor', 'plumbingWarmFloorArea'),
  pdf('ufh-connect-manifold', 'Подключение контура водяного тёплого пола к коллектору', 'комплекс', 3500, 'underfloor', 'manual'),
  pdf('ufh-opress-circuit', 'Опрессовка контура водяного тёплого пола', 'комплекс', 2500, 'underfloor', 'manual'),

  // —— Встроенные смесители ——
  pdf('hidden-mixer-body', 'Монтаж корпуса встроенного смесителя', 'шт.', 5000, 'hidden-mixer', 'plumbingMixersCount'),
  pdf('hidden-thermostat-body', 'Монтаж корпуса встроенного термостата', 'шт.', 6000, 'hidden-mixer', 'plumbingMixersCount'),
  pdf('hidden-hygiene-body', 'Монтаж корпуса встроенного гигиенического душа', 'шт.', 4500, 'hidden-mixer', 'plumbingMixersCount'),
  pdf('hidden-shower-block', 'Монтаж скрытого блока душевой системы', 'шт.', 6000, 'hidden-mixer', 'manual'),
  pdf('hidden-mixer-level', 'Выставление встроенного смесителя в проектную плоскость', 'шт.', 2500, 'hidden-mixer', 'plumbingMixersCount'),
  pdf('hidden-mixer-connect', 'Подключение встроенного смесителя к трубам водоснабжения', 'шт.', 3500, 'hidden-mixer', 'plumbingMixersCount'),
  pdf('hidden-embed', 'Монтаж закладной/крепления под встроенный сантехнический прибор', 'шт.', 2500, 'hidden-mixer', 'manual'),

  // —— Коллектор / учёт ——
  both(
    'manifold-cabinet-surface',
    'Монтаж коллекторного шкафа накладного',
    'шт.',
    3500,
    'manifold',
    'plumbingCollectorsCount',
    'santehmontazh',
  ),
  pdf('manifold-cabinet-flush', 'Монтаж коллекторного шкафа встроенного', 'шт.', 5500, 'manifold', 'plumbingCollectorsCount'),
  pdf('manifold-beam', 'Монтаж распределительной коллекторной балки', 'шт.', 5000, 'manifold', 'plumbingCollectorsCount'),
  pdf('manifold-inlet', 'Подключение вводной магистрали к коллекторной балке', 'шт.', 3500, 'manifold', 'plumbingCollectorsCount'),
  pdf('manifold-ball-valve', 'Монтаж шарового крана', 'шт.', 1200, 'manifold', 'manual'),
  pdf('manifold-filter-coarse', 'Монтаж фильтра грубой очистки', 'шт.', 1500, 'manifold', 'manual'),
  pdf('manifold-check-valve', 'Монтаж обратного клапана', 'шт.', 1500, 'manifold', 'manual'),
  pdf('manifold-reducer', 'Монтаж редуктора давления', 'шт.', 2500, 'manifold', 'manual'),
  pdf('manifold-filter-self', 'Монтаж фильтра самопромывного/магистрального', 'шт.', 3500, 'manifold', 'manual'),
  pdf('manifold-water-meter', 'Монтаж водомерного счётчика', 'шт.', 2500, 'manifold', 'manual'),
  pdf('manifold-hammer', 'Монтаж компенсатора гидроудара', 'шт.', 2000, 'manifold', 'manual'),
  pdf('manifold-servo', 'Монтаж крана с сервоприводом системы защиты от протечек', 'шт.', 3000, 'manifold', 'manual'),
  pdf('manifold-leak-sensor', 'Монтаж датчика протечки в зоне сантехники', 'шт.', 1500, 'manifold', 'manual'),

  // —— Инсталляция / трапы ——
  both(
    'install-frame',
    'Монтаж рамы инсталляции подвесного унитаза',
    'шт.',
    6500,
    'installation',
    'plumbingInstallationsCount',
    'santehmontazh',
  ),
  pdf('install-frame-level', 'Выставление рамы инсталляции в проектную плоскость', 'шт.', 2500, 'installation', 'plumbingInstallationsCount'),
  pdf('install-water-connect', 'Подключение инсталляции к водоснабжению', 'шт.', 2500, 'installation', 'plumbingInstallationsCount'),
  pdf('install-sewer-connect', 'Подключение инсталляции к канализации', 'шт.', 2500, 'installation', 'plumbingInstallationsCount'),
  pdf('install-hidden-siphon', 'Монтаж скрытого сифона кондиционера/ПММ/стиральной машины', 'шт.', 2500, 'installation', 'manual'),
  pdf('drain-point', 'Установка трапа точечного типа', 'шт.', 4500, 'installation', 'plumbingDrainsCount'),
  pdf('drain-slot', 'Установка трапа щелевого типа', 'шт.', 6500, 'installation', 'plumbingDrainsCount'),
  pdf('drain-level', 'Выставление трапа в проектную отметку', 'шт.', 2500, 'installation', 'plumbingDrainsCount'),
  pdf('drain-connect', 'Подключение трапа к канализации', 'шт.', 2500, 'installation', 'plumbingDrainsCount'),

  // —— Финишная сантехника ——
  pdf('finish-ball-valve', 'Установка финишных шаровых кранов в водорозетки', 'шт.', 900, 'finish', 'plumbingWaterPointsCount'),
  both(
    'finish-toilet-soft',
    'Установка чистового унитаза или биде на инсталляцию с кнопкой и крышкой',
    'шт.',
    5500,
    'finish',
    'plumbingToiletsCount',
    'santehmontazh',
  ),
  pdf('finish-electronic-lid', 'Установка электронной крышки унитаза', 'комплекс', 5250, 'finish', 'manual'),
  pdf('finish-bidet-mixer', 'Установка смесителя на биде', 'шт.', 3000, 'finish', 'plumbingMixersCount'),
  pdf('finish-hygiene-shower', 'Установка гигиенического душа', 'шт.', 3750, 'finish', 'plumbingMixersCount'),
  both(
    'finish-toilet-floor',
    'Установка напольного унитаза с подключением',
    'шт.',
    4500,
    'finish',
    'plumbingToiletsCount',
    'santehmontazh',
  ),
  pdf('finish-bidet-floor', 'Установка напольного биде с подключением', 'шт.', 4500, 'finish', 'manual'),
  pdf('finish-install-button', 'Установка кнопки инсталляции отдельно', 'шт.', 1500, 'finish', 'manual'),
  pdf('finish-toilet-lid', 'Установка сиденья/крышки унитаза отдельно', 'шт.', 1500, 'finish', 'manual'),
  pdf('finish-toilet-electronic', 'Установка электронного унитаза с подключением к готовым выводам', 'шт.', 9000, 'finish', 'plumbingToiletsCount'),
  pdf('finish-hygiene-hidden', 'Установка гигиенического душа скрытого монтажа, чистовая часть', 'комплекс', 2500, 'finish', 'plumbingMixersCount'),
  both(
    'finish-sink-ordinary',
    'Установка раковины (обычной) с подключением',
    'шт.',
    3500,
    'finish',
    'plumbingSinksCount',
    'santehmontazh',
  ),
  pdf('finish-sink-mixer', 'Установка смесителя на раковину', 'шт.', 3000, 'finish', 'plumbingMixersCount'),
  pdf('finish-siphon-chrome', 'Установка хромированного сифона', 'шт.', 3000, 'finish', 'manual'),
  pdf('finish-sink-wall', 'Установка подвесной раковины с подключением', 'шт.', 4500, 'finish', 'plumbingSinksCount'),
  pdf('finish-sink-countertop', 'Установка накладной раковины на столешницу с подключением', 'шт.', 3500, 'finish', 'plumbingSinksCount'),
  pdf('finish-sink-inset', 'Установка врезной раковины с подключением', 'шт.', 5500, 'finish', 'plumbingSinksCount'),
  pdf('finish-sink-over-washer', 'Установка раковины над стиральной машиной с подключением', 'шт.', 6000, 'finish', 'plumbingSinksCount'),
  pdf('finish-pedestal', 'Установка пьедестала или полупьедестала под раковину', 'шт.', 2500, 'finish', 'manual'),
  pdf('finish-bottom-valve', 'Установка донного клапана', 'шт.', 1800, 'finish', 'manual'),
  pdf('finish-siphon-sink', 'Установка сифона под раковину', 'шт.', 1500, 'finish', 'manual'),
  pdf('finish-siphon-bath', 'Установка сифона для ванны', 'шт.', 1500, 'finish', 'manual'),
  pdf('finish-siphon-tray', 'Установка сифона для душевого поддона', 'шт.', 1500, 'finish', 'manual'),
  both(
    'finish-kitchen-sink',
    'Установка кухонной мойки с подключением',
    'шт.',
    5250,
    'finish',
    'plumbingSinksCount',
    'santehmontazh',
  ),
  pdf('finish-kitchen-mixer', 'Установка кухонного смесителя', 'шт.', 3000, 'finish', 'plumbingMixersCount'),
  pdf('finish-mixer-pullout', 'Установка смесителя с выдвижной лейкой', 'шт.', 3750, 'finish', 'plumbingMixersCount'),
  pdf('finish-dispenser', 'Установка дозатора моющего средства', 'шт.', 1200, 'finish', 'manual'),
  pdf('finish-food-waste', 'Установка измельчителя пищевых отходов с подключением', 'шт.', 7000, 'finish', 'manual'),
  pdf('finish-water-filter', 'Установка фильтра питьевой воды под мойку', 'шт.', 4500, 'finish', 'manual'),
  pdf('finish-drinking-tap', 'Установка крана питьевой воды', 'шт.', 2500, 'finish', 'manual'),
  both(
    'finish-washer',
    'Установка и подключение стиральной или сушильной машины с промывкой',
    'шт.',
    4500,
    'finish',
    'plumbingWasherConnectionsCount',
    'santehmontazh',
  ),
  pdf('finish-towel-water', 'Монтаж водяного полотенцесушителя', 'шт.', 7500, 'finish', 'plumbingTowelWarmersCount'),
  pdf('towel-outlets-mount', 'Монтаж выводов под водяной полотенцесушитель', 'комплекс', 5500, 'connections', 'manual'),
  pdf('towel-bypass-mount', 'Монтаж байпаса полотенцесушителя', 'шт.', 4500, 'connections', 'manual'),
  pdf('towel-node-pressure-test', 'Опрессовка узла полотенцесушителя', 'комплекс', 2500, 'check', 'manual'),
  pdf('finish-dishwasher', 'Подключение посудомоечной машины к готовым выводам', 'шт.', 4500, 'finish', 'plumbingDishwasherConnectionsCount'),
  pdf('finish-towel-reflectors', 'Установка декоративных отражателей на выводы полотенцесушителя', 'комплекс', 1200, 'finish', 'manual'),
  pdf('finish-heater-flow', 'Установка проточного водонагревателя к готовым выводам', 'шт.', 4500, 'finish', 'plumbingWaterHeatersCount'),
  pdf('finish-heater-50', 'Установка накопительного водонагревателя до 50 л к готовым выводам', 'шт.', 6000, 'finish', 'plumbingWaterHeatersCount'),
  pdf('finish-heater-50-100', 'Установка накопительного водонагревателя 50–100 л к готовым выводам', 'шт.', 7500, 'finish', 'plumbingWaterHeatersCount'),
  pdf('finish-heater-100-plus', 'Установка накопительного водонагревателя свыше 100 л к готовым выводам', 'шт.', 9750, 'finish', 'plumbingWaterHeatersCount'),
  pdf('finish-bath-guides', 'Монтаж направляющих для установки ванной', 'комплекс', 2250, 'finish', 'manual'),
  both(
    'finish-bath-cast-iron',
    'Установка ванны чугунной с подключением',
    'шт.',
    18000,
    'finish',
    'plumbingBathtubsCount',
    'santehmontazh',
  ),
  both(
    'finish-bath-acrylic',
    'Установка ванны акриловой с подключением',
    'шт.',
    13500,
    'finish',
    'plumbingBathtubsCount',
    'santehmontazh',
  ),
  pdf('finish-bath-mixer-floor', 'Установка напольного смесителя', 'шт.', 3000, 'finish', 'plumbingMixersCount'),
  pdf('finish-bath-mixer', 'Установка смесителя на ванну', 'шт.', 3000, 'finish', 'plumbingMixersCount'),
  pdf('finish-bath-overflow', 'Установка слив-перелива ванны', 'шт.', 3750, 'finish', 'manual'),
  pdf('finish-bath-panel', 'Установка фронтальной панели ванны', 'шт.', 3750, 'finish', 'manual'),
  pdf('finish-bath-level', 'Выставление и регулировка ванны по уровню', 'шт.', 3750, 'finish', 'plumbingBathtubsCount'),
  pdf('finish-bath-seal', 'Герметизация примыкания ванны к стене', 'м. пог.', 1050, 'finish', 'manual'),
  pdf('finish-bath-quaryl', 'Установка ванны из кварила или искусственного камня с подключением', 'шт.', 15750, 'finish', 'plumbingBathtubsCount'),
  both(
    'finish-shower-tray',
    'Установка готового душевого поддона с подключением',
    'шт.',
    12750,
    'finish',
    'plumbingShowersCount',
    'santehmontazh',
  ),
  both(
    'finish-shower-cabin',
    'Установка душевой кабины с подключением',
    'шт.',
    19500,
    'finish',
    'plumbingShowersCount',
    'santehmontazh',
  ),
  pdf('finish-shower-stand', 'Установка душевой стойки душа', 'шт.', 4500, 'finish', 'manual'),
  pdf('finish-shower-rain', 'Установка душевой стойки с лейкой «тропический дождь»', 'шт.', 4500, 'finish', 'manual'),
  pdf('finish-ibox', 'Установка чистовых элементов скрытых смесителей, iBox (излив, ручка, смеситель)', 'комплекс', 6000, 'finish', 'plumbingMixersCount'),
  pdf('finish-jet', 'Установка отдельных форсунок', 'шт.', 3000, 'finish', 'manual'),
  pdf('finish-shower-mixer-open', 'Установка душевого смесителя наружного монтажа', 'шт.', 3750, 'finish', 'plumbingMixersCount'),
  pdf('finish-thermostat-mixer', 'Установка термостатического смесителя', 'шт.', 5250, 'finish', 'plumbingMixersCount'),
  pdf('finish-hidden-shower-face', 'Установка чистовой части встроенного душевого смесителя', 'комплекс', 6750, 'finish', 'plumbingMixersCount'),
  pdf('finish-hidden-thermostat-face', 'Установка чистовой части встроенного термостата', 'комплекс', 7500, 'finish', 'plumbingMixersCount'),
  pdf('finish-shower-handset', 'Установка душевой лейки с держателем', 'шт.', 3000, 'finish', 'manual'),
  pdf('finish-shower-spout', 'Установка настенного душевого излива', 'шт.', 3750, 'finish', 'manual'),
  pdf('finish-drain-grate', 'Установка декоративной решетки душевого трапа', 'шт.', 1800, 'finish', 'plumbingDrainsCount'),
  both(
    'finish-glass-partition',
    'Установка стеклянной душевой шторки или неподвижной перегородки',
    'шт.',
    15000,
    'finish',
    'plumbingShowersCount',
    'santehmontazh',
  ),
  pdf('finish-glass-door', 'Установка стеклянной душевой перегородки с дверью, душевого уголка или раздвижной системы', 'шт.', 22500, 'finish', 'plumbingShowersCount'),
  pdf('finish-seal-fixture', 'Герметизация примыкания сантехнического оборудования силиконовым герметиком', 'м. пог.', 1050, 'finish', 'manual'),

  // —— Проверки / пуск ——
  pdf('check-system', 'Проверка сантехнической системы после монтажа', 'комплекс', 3500, 'check', 'manual'),
  pdf('check-water-start', 'Пуск системы водоснабжения после монтажа', 'комплекс', 3500, 'check', 'manual'),
  pdf('check-local-adjust', 'Локальная регулировка сантехнического узла после монтажа', 'шт.', 1500, 'check', 'manual'),
  pdf('check-finish', 'Настройка и проверка финишной сантехники после монтажа', 'комплекс', 2250, 'check', 'manual'),
  pdf('check-leak', 'Пуск и проверка оборудования на протечки', 'комплекс', 2250, 'check', 'manual'),
]
