import type { TilePriceMappingItem } from '../shared/estimate.types'

export const TILE_SECTION_ID = 'tile'
export const TILE_SECTION_TITLE = 'Плитка (labour)'

/**
 * Whitelist labour-работ по плитке для внутреннего калькулятора.
 * Primary: PDF `anfas-price-list.pdf`. Frontend — сверка при `source=both`.
 * Вне scope: гидро, СВП, мембраны, металлопрофили, люки, экраны, фартук-комплекс, материалы.
 */
export const TILE_PRICE_MAPPING: readonly TilePriceMappingItem[] = [
  // —— Демонтаж ——
  {
    id: 'demolition-floor-tile',
    title: 'Демонтаж плитки пола',
    unit: 'м²',
    unitPrice: 900,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж плитки пола',
    frontendUnitPrice: 900,
    defaultEnabled: false,
    defaultQuantityFrom: 'floorTileArea',
  },
  {
    id: 'demolition-wall-tile',
    title: 'Демонтаж плитки стеновой',
    unit: 'м²',
    unitPrice: 900,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж плитки стеновой',
    frontendUnitPrice: 900,
    note: 'PDF 2026-07-29 и FE: 900 ₽/м²',
    defaultEnabled: false,
    defaultQuantityFrom: 'wallTileArea',
  },
  {
    id: 'demolition-tile-adhesive',
    title: 'Демонтаж плиточного клея',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },

  // —— Подготовка ——
  {
    id: 'prep-dust',
    title: 'Обеспыливание поверхности перед плиточными работами',
    unit: 'м²',
    unitPrice: 100,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-primer',
    title: 'Грунтование поверхности перед плиточными работами',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-betonkontakt',
    title: 'Нанесение бетонконтакта перед плиточными работами',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'prep',
    note: 'Labour only; материал праймера не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-local-clean',
    title: 'Локальная зачистка основания перед плиточными работами',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-local-grind',
    title: 'Локальная шлифовка основания перед плиточными работами',
    unit: 'м²',
    unitPrice: 450,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-plane-check',
    title: 'Проверка плоскости основания перед плиточными работами',
    unit: 'м²',
    unitPrice: 100,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-layout',
    title: 'Разметка и раскладка плитки перед облицовкой',
    unit: 'м²',
    unitPrice: 250,
    source: 'both',
    kind: 'prep',
    frontendCategorySlug: 'plitka',
    frontendName: 'Разметка и раскладка плитки перед облицовкой',
    frontendUnitPrice: 250,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'prep-notching',
    title: 'Устройство насечек на гладком основании перед плиточными работами',
    unit: 'м²',
    unitPrice: 400,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },

  // —— Облицовка ——
  {
    id: 'clad-301-1300',
    title: 'Облицовка керамической плиткой или керамогранитом диагональю 301–1300 мм',
    unit: 'м²',
    unitPrice: 4800,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка керамической плиткой или керамогранитом диагональю 301–1300 мм',
    frontendUnitPrice: 4800,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-1301-1700',
    title: 'Облицовка плиткой диагональю 1301–1700 мм',
    unit: 'м²',
    unitPrice: 5000,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка плиткой диагональю 1301–1700 мм',
    frontendUnitPrice: 5000,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-1701-3600',
    title: 'Облицовка крупноформатной плитой диагональю 1701–3600 мм',
    unit: 'м²',
    unitPrice: 6000,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка крупноформатной плиткой диагональю 1701–3600 мм',
    frontendUnitPrice: 6000,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-over-3600',
    title: 'Облицовка плиткой диагональю свыше 3600 мм',
    unit: 'м²',
    unitPrice: 7500,
    source: 'pdf',
    kind: 'cladding',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-mosaic',
    title: 'Облицовка мозаикой на сетке',
    unit: 'м²',
    unitPrice: 4500,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка мозаикой на сетке',
    frontendUnitPrice: 4500,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-small-format',
    title: 'Облицовка мелкоштучной плиткой типа кабанчик/гексагон/ёлка',
    unit: 'м²',
    unitPrice: 5600,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка мелкоштучной плиткой типа кабанчик/гексагон/ёлка',
    frontendUnitPrice: 5600,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-small-volume',
    title: 'Облицовка плиткой при малом объёме работ до 5 м²',
    unit: 'м²',
    unitPrice: 5500,
    source: 'pdf',
    kind: 'cladding',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-steps',
    title: 'Облицовка ступеней керамогранитом',
    unit: 'м. пог.',
    unitPrice: 4800,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка ступеней керамогранитом',
    frontendUnitPrice: 4800,
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'clad-slopes',
    title: 'Облицовка откосов плиткой',
    unit: 'м. пог.',
    unitPrice: 5100,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка откосов плиткой',
    frontendUnitPrice: 5100,
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'clad-shower-tray',
    title: 'Облицовка душевого поддона плиткой или мозаикой',
    unit: 'м²',
    unitPrice: 4500,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Облицовка душевого поддона плиткой или мозаикой',
    frontendUnitPrice: 4500,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'clad-shower-edge',
    title: 'Облицовка борта душевого поддона',
    unit: 'м. пог.',
    unitPrice: 3000,
    source: 'pdf',
    kind: 'cladding',
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'surcharge-diagonal',
    title: 'Надбавка за укладку плитки по диагонали',
    unit: 'м²',
    unitPrice: 800,
    source: 'both',
    kind: 'cladding',
    frontendCategorySlug: 'plitka',
    frontendName: 'Надбавка за укладку плитки по диагонали',
    frontendUnitPrice: 800,
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'surcharge-rectified',
    title: 'Надбавка за укладку ректифицированной плитки / минимальный шов',
    unit: 'м²',
    unitPrice: 600,
    source: 'pdf',
    kind: 'cladding',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },

  // —— Рез / отверстия ——
  {
    id: 'cut-edge-ceramic',
    title: 'Подготовка чистового края керамической/керамогранитной плитки',
    unit: 'м. пог.',
    unitPrice: 1500,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'cut-edge-large-small',
    title: 'Подготовка чистового края крупноформатной или мелкоштучной плитки',
    unit: 'м. пог.',
    unitPrice: 1800,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'cut-45-ceramic',
    title: 'Заусовка 45° керамической плитки',
    unit: 'м. пог.',
    unitPrice: 2500,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'cut-45-porcelain',
    title: 'Заусовка 45° керамогранита',
    unit: 'м. пог.',
    unitPrice: 2600,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'cut-45-large',
    title: 'Заусовка 45° крупноформатной плитки',
    unit: 'м. пог.',
    unitPrice: 3000,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cuttingLength',
  },
  {
    id: 'hole-up-to-100',
    title: 'Выпил отверстия в плитке диаметром до 100 мм',
    unit: 'шт.',
    unitPrice: 900,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'holesCount',
  },
  {
    id: 'hole-100-230',
    title: 'Выпил отверстия в плитке диаметром 100–230 мм',
    unit: 'шт.',
    unitPrice: 1300,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'holesCount',
  },
  {
    id: 'hole-rect',
    title: 'Выпил прямоугольного отверстия в плитке',
    unit: 'шт.',
    unitPrice: 1500,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'holesCount',
  },

  // —— Углы ——
  {
    id: 'corner-outer-surcharge',
    title: 'Надбавка за формирование внешнего угла при работах с плиткой',
    unit: 'м. пог.',
    unitPrice: 1200,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'corner-cement',
    title: 'Формирование внешнего угла цементной затиркой',
    unit: 'м. пог.',
    unitPrice: 700,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'corner-epoxy',
    title: 'Формирование внешнего угла эпоксидной затиркой',
    unit: 'м. пог.',
    unitPrice: 1200,
    source: 'pdf',
    kind: 'cutting',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },

  // —— Плинтус / бордюр ——
  {
    id: 'plinth-ready',
    title: 'Укладка готовых бордюров/плинтусов из плитки высотой до 300 мм',
    unit: 'м. пог.',
    unitPrice: 1800,
    source: 'both',
    kind: 'accessory',
    frontendCategorySlug: 'plitka',
    frontendName: 'Укладка готовых бордюров/плинтусов из плитки высотой до 300 мм',
    frontendUnitPrice: 1800,
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'plinth-make-kg',
    title: 'Изготовление плинтуса/бордюра из керамогранита',
    unit: 'м. пог.',
    unitPrice: 1600,
    source: 'pdf',
    kind: 'accessory',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'plinth-mount-kg',
    title: 'Монтаж плинтуса/бордюра из керамогранита',
    unit: 'м. пог.',
    unitPrice: 1800,
    source: 'pdf',
    kind: 'accessory',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },

  // —— Затирка ——
  {
    id: 'grout-protect',
    title: 'Защита плитки перед затиркой швов',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'grout',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-cement',
    title: 'Заполнение/затирка межплиточных швов цементными составами',
    unit: 'м²',
    unitPrice: 550,
    source: 'both',
    kind: 'grout',
    frontendCategorySlug: 'plitka',
    frontendName: 'Заполнение/затирка межплиточных швов цементными составами',
    frontendUnitPrice: 550,
    note: 'Labour only; затирка как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-cement-small',
    title: 'Затирка цементная по мелкоштучной плитке (кабанчик/ёлка)',
    unit: 'м²',
    unitPrice: 1500,
    source: 'pdf',
    kind: 'grout',
    note: 'Labour only; затирка как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-epoxy',
    title: 'Заполнение/затирка межплиточных швов двухкомпонентными эпоксидными составами',
    unit: 'м²',
    unitPrice: 1600,
    source: 'both',
    kind: 'grout',
    frontendCategorySlug: 'plitka',
    frontendName:
      'Заполнение/затирка межплиточных швов двухкомпонентными эпоксидными составами',
    frontendUnitPrice: 1600,
    note: 'Labour only; затирка как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-epoxy-small',
    title: 'Затирка эпоксидная по мелкоштучной плитке',
    unit: 'м²',
    unitPrice: 2000,
    source: 'pdf',
    kind: 'grout',
    note: 'Labour only; затирка как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-epoxy-mosaic',
    title: 'Затирка эпоксидная по мозаике',
    unit: 'м²',
    unitPrice: 2500,
    source: 'pdf',
    kind: 'grout',
    note: 'Labour only; затирка как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-clean-cement',
    title: 'Очистка плитки после цементной затирки',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'grout',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-clean-epoxy',
    title: 'Очистка плитки после эпоксидной затирки',
    unit: 'м²',
    unitPrice: 500,
    source: 'pdf',
    kind: 'grout',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },
  {
    id: 'grout-seal',
    title: 'Нанесение защитного состава на межплиточные швы',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'grout',
    defaultEnabled: false,
    defaultQuantityFrom: 'cladArea',
  },

  // —— Герметизация ——
  {
    id: 'seal-prep',
    title: 'Подготовка примыканий под герметизацию',
    unit: 'м. пог.',
    unitPrice: 200,
    source: 'pdf',
    kind: 'seal',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'seal-silicone',
    title: 'Герметизация примыканий силиконовым герметиком',
    unit: 'м. пог.',
    unitPrice: 600,
    source: 'pdf',
    kind: 'seal',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'seal-polyurethane',
    title: 'Герметизация примыканий полиуретановым герметиком',
    unit: 'м. пог.',
    unitPrice: 800,
    source: 'pdf',
    kind: 'seal',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'seal-tape',
    title: 'Проклейка примыканий лентой',
    unit: 'м. пог.',
    unitPrice: 250,
    source: 'pdf',
    kind: 'seal',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'seal-bath',
    title: 'Герметизация примыкания ванны к стене',
    unit: 'м. пог.',
    unitPrice: 1050,
    source: 'pdf',
    kind: 'seal',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'seal-door',
    title: 'Герметизация примыкания дверного блока',
    unit: 'м. пог.',
    unitPrice: 350,
    source: 'pdf',
    kind: 'seal',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },

  // —— Ремонт ——
  {
    id: 'repair-joint',
    title: 'Локальное восстановление межплиточного шва',
    unit: 'м. пог.',
    unitPrice: 600,
    source: 'pdf',
    kind: 'repair',
    defaultEnabled: false,
    defaultQuantityFrom: 'cornerLength',
  },
  {
    id: 'repair-one-tile',
    title: 'Локальная замена одной плитки без демонтажа соседних',
    unit: 'шт.',
    unitPrice: 3500,
    source: 'both',
    kind: 'repair',
    frontendCategorySlug: 'plitka',
    frontendName: 'Локальная замена одной плитки без демонтажа соседних',
    frontendUnitPrice: 3500,
    defaultEnabled: false,
    defaultQuantityFrom: 'repairCount',
  },
]
