import type { WallPriceMappingItem } from '../shared/estimate.types'

export const WALL_SECTION_ID = 'walls'
export const WALL_SECTION_TITLE = 'Стены (черновые / подготовка / финиш labour)'

/**
 * Явный whitelist работ по стенам для внутреннего калькулятора.
 * Основной источник: PDF `anfas-price-list.pdf`. `prices.data.ts` — сверка при `source` both.
 * Материалы, декоративные покрытия, плитка, ГКл-перегородки и т.п. — вне scope.
 * Покраска/обои — только labour (`materialsExcluded` в результате сметы).
 */
export const WALL_PRICE_MAPPING: readonly WallPriceMappingItem[] = [
  // —— Демонтаж ——
  {
    id: 'demolition-wallpaper',
    title: 'Демонтаж обоев',
    unit: 'м²',
    unitPrice: 250,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж обоев',
    frontendUnitPrice: 250,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-paint',
    title: 'Демонтаж краски',
    unit: 'м²',
    unitPrice: 400,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж краски',
    frontendUnitPrice: 400,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-plaster',
    title: 'Демонтаж штукатурки стен',
    unit: 'м²',
    unitPrice: 700,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж штукатурки стен',
    frontendUnitPrice: 700,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-wall-tile',
    title: 'Демонтаж плитки стеновой',
    unit: 'м²',
    unitPrice: 900,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж плитки стеновой',
    frontendUnitPrice: 900,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-glassfiber',
    title: 'Демонтаж стеклохолста',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-paint-mesh',
    title: 'Демонтаж малярной сетки',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-plaster-slopes',
    title: 'Демонтаж штукатурки с откосов',
    unit: 'м. пог.',
    unitPrice: 720,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },
  {
    id: 'demolition-panels-slopes',
    title: 'Демонтаж панелей и уголков с откосов',
    unit: 'м. пог.',
    unitPrice: 200,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },
  {
    id: 'demolition-slopes',
    title: 'Демонтаж откосов (гипсокартон, штукатурка)',
    unit: 'м. пог.',
    unitPrice: 200,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },

  // —— Подготовка основания ——
  {
    id: 'prep-paint-strip',
    title: 'Зачистка краски со стен',
    unit: 'м²',
    unitPrice: 450,
    source: 'both',
    kind: 'prep',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Зачистка краски со стен',
    frontendUnitPrice: 450,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'prep-diamond-grind',
    title: 'Шлифование алмазными чашками стеновых поверхностей',
    unit: 'м²',
    unitPrice: 500,
    source: 'both',
    kind: 'prep',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Шлифование алмазными чашками стеновых поверхностей',
    frontendUnitPrice: 500,
    defaultEnabled: false,
    defaultQuantityFrom: 'totalWallArea',
  },
  {
    id: 'prep-dust-removal',
    title: 'Обеспыливание поверхности перед грунтованием или шпаклеванием',
    unit: 'м²',
    unitPrice: 70,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'prep-sand-plaster',
    title: 'Ошкуривание штукатурки перед шпаклеванием',
    unit: 'м²',
    unitPrice: 180,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },

  // —— Грунтование ——
  {
    id: 'primer-deep-penetration',
    title: 'Грунтование основания грунтовкой глубокого проникновения',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'totalWallArea',
  },
  {
    id: 'primer-one-layer',
    title: 'Грунтование поверхностей в 1 слой',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'primer-adhesion-sous-couche',
    title: 'Нанесение адгезионного праймера / Sous-Couche под окраску',
    unit: 'м²',
    unitPrice: 180,
    source: 'pdf',
    kind: 'primer',
    note: 'Labour only; материал праймера не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'primer-before-contact',
    title: 'Грунтование основания перед нанесением контактного слоя',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'primer-gypsum-plaster',
    title: 'Грунтование поверхностей под оштукатуривание гипсовыми смесями',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },

  // —— Штукатурка ——
  {
    id: 'plaster-contact-layer',
    title: 'Нанесение контактного слоя клеевыми составами перед оштукатуриванием',
    unit: 'м²',
    unitPrice: 240,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Нанесение контактного слоя клеевыми составами перед оштукатуриванием',
    frontendUnitPrice: 240,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-mesh-reinforce',
    title: 'Армирование стеклотканевой или базальтовой сеткой в толще штукатурки',
    unit: 'м²',
    unitPrice: 240,
    source: 'both',
    kind: 'reinforce',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Армирование стеклотканевой или базальтовой сеткой в толще штукатурки',
    frontendUnitPrice: 240,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-gypsum-beacons',
    title: 'Монтаж штукатурных маяков под гипсовую штукатурку',
    unit: 'м²',
    unitPrice: 160,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Монтаж штукатурных маяков под гипсовую штукатурку',
    frontendUnitPrice: 160,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-gypsum-main',
    title: 'Оштукатуривание поверхностей стен гипсовыми смесями (слой до 40 мм)',
    unit: 'м²',
    unitPrice: 700,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Оштукатуривание поверхностей стен гипсовыми смесями (слой до 40 мм)',
    frontendUnitPrice: 700,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-gypsum-narrow',
    title: 'Оштукатуривание узких поверхностей (Ш<600 мм) гипсовыми смесями',
    unit: 'м. пог.',
    unitPrice: 850,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Оштукатуривание узких поверхностей (Ш<600 мм) гипсовыми смесями',
    frontendUnitPrice: 850,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'plaster-gypsum-extra',
    title: 'Дополнительный слой гипсовой штукатурки свыше 40 мм',
    unit: 'м²',
    unitPrice: 240,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Дополнительный слой гипсовой штукатурки свыше 40 мм',
    frontendUnitPrice: 240,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-gypsum-corners',
    title: 'Выведение углов 90° при оштукатуривании гипсовыми смесями',
    unit: 'м. пог.',
    unitPrice: 650,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Выведение углов 90° при оштукатуривании гипсовыми смесями',
    frontendUnitPrice: 650,
    defaultEnabled: false,
    defaultQuantityFrom: 'cornersLength',
  },
  {
    id: 'plaster-gypsum-beacon-removal',
    title: 'Демонтаж штукатурных маяков после оштукатуривания',
    unit: 'м²',
    unitPrice: 100,
    source: 'pdf',
    kind: 'plaster-gypsum',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-cement-beacons',
    title: 'Монтаж штукатурных маяков под цементно-песчаную штукатурку',
    unit: 'м²',
    unitPrice: 160,
    source: 'pdf',
    kind: 'plaster-cement',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-cement-main',
    title: 'Оштукатуривание поверхностей стен цементно-песчаными смесями (слой до 40 мм)',
    unit: 'м²',
    unitPrice: 800,
    source: 'both',
    kind: 'plaster-cement',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Оштукатуривание поверхностей стен цементно-песчаными смесями (слой до 40 мм)',
    frontendUnitPrice: 800,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-cement-narrow',
    title: 'Оштукатуривание узких поверхностей (Ш<300 мм) цементно-песчаными смесями',
    unit: 'м. пог.',
    unitPrice: 715,
    source: 'both',
    kind: 'plaster-cement',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Оштукатуривание узких поверхностей (Ш<300 мм) цементно-песчаными смесями',
    frontendUnitPrice: 715,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'plaster-cement-extra',
    title: 'Дополнительный слой цементно-песчаной штукатурки свыше 40 мм',
    unit: 'м²',
    unitPrice: 290,
    source: 'both',
    kind: 'plaster-cement',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Дополнительный слой цементно-песчаной штукатурки свыше 40 мм',
    frontendUnitPrice: 290,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-cement-corners',
    title: 'Выведение углов 90° при оштукатуривании цементно-песчаными смесями',
    unit: 'м. пог.',
    unitPrice: 325,
    source: 'both',
    kind: 'plaster-cement',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Выведение углов 90° при оштукатуривании цементно-песчаными смесями',
    frontendUnitPrice: 325,
    defaultEnabled: false,
    defaultQuantityFrom: 'cornersLength',
  },
  {
    id: 'plaster-local-fix',
    title: 'Локальное исправление плоскости после оштукатуривания',
    unit: 'м²',
    unitPrice: 240,
    source: 'both',
    kind: 'plaster-gypsum',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Локальное исправление плоскости после оштукатуривания',
    frontendUnitPrice: 240,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },

  // —— Шпаклёвка / шлифовка ——
  {
    id: 'putty-gkl-joint-expand',
    title: 'Расшивка незаводских швов гипсокартона под шпаклевание',
    unit: 'м. пог.',
    unitPrice: 160,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Расшивка незаводских швов гипсокартона под шпаклевание',
    frontendUnitPrice: 160,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'putty-base-1',
    title: 'Нанесение базовой шпаклевки стен, 1 слой',
    unit: 'м²',
    unitPrice: 350,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Нанесение базовой шпаклевки стен, 1 слой',
    frontendUnitPrice: 350,
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-base-2',
    title: 'Нанесение базовой шпаклевки стен, 2 слоя',
    unit: 'м²',
    unitPrice: 700,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Нанесение базовой шпаклевки стен, 2 слоя',
    frontendUnitPrice: 700,
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-finish-1',
    title: 'Нанесение финишной шпаклевки на стены, 1 слой',
    unit: 'м²',
    unitPrice: 350,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Нанесение финишной шпаклевки на стены, 1 слой',
    frontendUnitPrice: 350,
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-finish-2',
    title: 'Нанесение финишной шпаклевки на стены 2 слоя',
    unit: 'м²',
    unitPrice: 700,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-sanding',
    title: 'Шлифовка стен после шпаклевания',
    unit: 'м²',
    unitPrice: 220,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Шлифовка стен после шпаклевания',
    frontendUnitPrice: 220,
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-finish-sanding',
    title: 'Финишная шлифовка стен',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-local-3mm',
    title: 'Локальное выравнивание поверхности шпаклевочной смесью до 3 мм',
    unit: 'м²',
    unitPrice: 380,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-slopes-2',
    title: 'Шпаклевание откосов 2 слоя',
    unit: 'м. пог.',
    unitPrice: 700,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },
  {
    id: 'putty-sanding-slopes',
    title: 'Шлифовка откосов и узких поверхностей',
    unit: 'м. пог.',
    unitPrice: 250,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },

  // —— Армирование / холст ——
  {
    id: 'reinforce-glassfiber',
    title: 'Монтаж стеклохолста на стены',
    unit: 'м²',
    unitPrice: 450,
    source: 'both',
    kind: 'reinforce',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Монтаж стеклохолста на стены',
    frontendUnitPrice: 450,
    note: 'Labour only; материал холста не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'reinforce-paint-mesh',
    title: 'Монтаж малярной сетки в слой шпаклевки',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'reinforce',
    note: 'Labour only; материал сетки не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },

  // —— Откосы ——
  {
    id: 'slopes-sandwich',
    title: 'Монтаж откосов из сэндвич-панелей на подготовленную поверхность',
    unit: 'м. пог.',
    unitPrice: 1200,
    source: 'both',
    kind: 'slopes',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Монтаж откосов из сэндвич-панелей на подготовленную поверхность',
    frontendUnitPrice: 1200,
    note: 'Labour; панели как материал не считаем отдельной строкой',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },
  {
    id: 'slopes-ruspanel',
    title: 'Монтаж откосов из Ruspanel (руспанель) на подготовленную поверхность',
    unit: 'м. пог.',
    unitPrice: 1500,
    source: 'both',
    kind: 'slopes',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Монтаж откосов из Ruspanel (руспанель) на подготовленную поверхность',
    frontendUnitPrice: 1500,
    note: 'Labour; панели как материал не считаем отдельной строкой',
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },
  {
    id: 'slopes-gasblock',
    title: 'Наращивание откоса газобетонным блоком',
    unit: 'м. пог.',
    unitPrice: 3500,
    source: 'both',
    kind: 'slopes',
    frontendCategorySlug: 'shtukaturka',
    frontendName: 'Наращивание откоса газобетонным блоком',
    frontendUnitPrice: 3500,
    defaultEnabled: false,
    defaultQuantityFrom: 'slopesLength',
  },

  // —— Finish labour: покраска ——
  {
    id: 'paint-1',
    title: 'Покраска стен валиком, 1 слой',
    unit: 'м²',
    unitPrice: 260,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Покраска стен валиком, 1 слой',
    frontendUnitPrice: 260,
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'paint-2',
    title: 'Покраска стен валиком, 2 слоя',
    unit: 'м²',
    unitPrice: 480,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Покраска стен валиком, 2 слоя',
    frontendUnitPrice: 480,
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'paint-3',
    title: 'Покраска стен валиком, 3 слоя',
    unit: 'м²',
    unitPrice: 650,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Покраска стен валиком, 3 слоя',
    frontendUnitPrice: 650,
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'paint-mech-2',
    title: 'Механизированная покраска стен, 2 слоя',
    unit: 'м²',
    unitPrice: 750,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Механизированная покраска стен, 2 слоя',
    frontendUnitPrice: 750,
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'finish-flizelin-under-paint',
    title: 'Оклейка стен малярным флизелином (обои под покраску)',
    unit: 'м²',
    unitPrice: 800,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Оклейка стен малярным флизелином (обои под покраску)',
    frontendUnitPrice: 800,
    note: 'Labour only; флизелин как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'finish-check-light',
    title: 'Проверка поверхности под покраску проявочным светом',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'finish-paint',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },

  // —— Finish labour: обои ——
  {
    id: 'wallpaper-flizelin',
    title: 'Поклейка флизелиновых обоев без подбора рисунка',
    unit: 'м²',
    unitPrice: 800,
    source: 'both',
    kind: 'finish-wallpaper',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Поклейка флизелиновых обоев без подбора рисунка',
    frontendUnitPrice: 800,
    note: 'Labour only; обои как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'wallpaper-vinyl-match',
    title: 'Поклейка виниловых обоев с подбором рисунка',
    unit: 'м²',
    unitPrice: 950,
    source: 'both',
    kind: 'finish-wallpaper',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Поклейка виниловых обоев с подбором рисунка',
    frontendUnitPrice: 950,
    note: 'Labour only; обои как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'wallpaper-photo',
    title: 'Поклейка фотообоев',
    unit: 'м²',
    unitPrice: 1000,
    source: 'both',
    kind: 'finish-wallpaper',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Поклейка фотообоев',
    frontendUnitPrice: 1000,
    note: 'Labour only; обои как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'wallpaper-textile-match',
    title: 'Поклейка тканевых обоев с подбором рисунка',
    unit: 'м²',
    unitPrice: 1550,
    source: 'both',
    kind: 'finish-wallpaper',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Поклейка тканевых обоев с подбором рисунка',
    frontendUnitPrice: 1550,
    note: 'Labour only; обои как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
]
