import type { CeilingPriceMappingItem } from '../shared/estimate.types'

export const CEILING_SECTION_ID = 'ceilings'
export const CEILING_SECTION_TITLE = 'Потолки (черновые / подготовка / финиш labour)'

/**
 * Whitelist labour-работ по потолкам для внутреннего калькулятора.
 * Primary: PDF `anfas-price-list.pdf`. Frontend — сверка при `source=both`.
 * Вне scope: ГКЛ-пакеты, карнизы, Armstrong/Грильято монтаж, натяжной монтаж, кабель, материалы.
 */
export const CEILING_PRICE_MAPPING: readonly CeilingPriceMappingItem[] = [
  // —— Демонтаж ——
  {
    id: 'demolition-paint',
    title: 'Демонтаж краски потолка',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-plaster',
    title: 'Демонтаж штукатурки потолка',
    unit: 'м²',
    unitPrice: 900,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-putty',
    title: 'Демонтаж шпаклевки потолка',
    unit: 'м²',
    unitPrice: 400,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-wallpaper',
    title: 'Демонтаж обоев с потолка',
    unit: 'м²',
    unitPrice: 320,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-gkl-frame',
    title: 'Демонтаж ГКЛ потолка с каркасом',
    unit: 'м²',
    unitPrice: 1300,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж ГКЛ потолка с каркасом',
    frontendUnitPrice: 1300,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-suspended',
    title: 'Демонтаж подвесных потолков (Армстронг/Грильято)',
    unit: 'м²',
    unitPrice: 400,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж подвесных потолков (Армстронг/Грильято)',
    frontendUnitPrice: 400,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-stretch',
    title: 'Демонтаж натяжного потолка',
    unit: 'м²',
    unitPrice: 250,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж натяжного потолка',
    frontendUnitPrice: 250,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-stretch-no-save',
    title: 'Демонтаж натяжного потолка без сохранения (включая профиль)',
    unit: 'м²',
    unitPrice: 200,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-panel',
    title: 'Демонтаж панельного потолка',
    unit: 'м²',
    unitPrice: 400,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },

  // —— Подготовка ——
  {
    id: 'prep-diamond-grind',
    title: 'Шлифование алмазными чашками потолочных поверхностей с целью подготовки основания',
    unit: 'м²',
    unitPrice: 800,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'totalCeilingArea',
  },
  {
    id: 'prep-dust-removal',
    title: 'Обеспыливание поверхности перед грунтованием или шпаклеванием',
    unit: 'м²',
    unitPrice: 70,
    source: 'pdf',
    kind: 'prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },

  // —— Грунт ——
  {
    id: 'primer-deep-penetration',
    title: 'Грунтование основания грунтовкой глубокого проникновения',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'totalCeilingArea',
  },
  {
    id: 'primer-one-layer',
    title: 'Грунтование поверхностей в 1 слой',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'primer-plaster-ceiling',
    title: 'Грунтование наклонных/потолочных поверхностей под оштукатуривание',
    unit: 'м²',
    unitPrice: 105,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },

  // —— Штукатурка ——
  {
    id: 'plaster-beacons-ceiling',
    title: 'Монтаж штукатурных маяков на наклонных/потолочных поверхностях',
    unit: 'м²',
    unitPrice: 210,
    source: 'pdf',
    kind: 'plaster',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-beacon-removal-ceiling',
    title: 'Демонтаж штукатурных маяков на наклонных/потолочных поверхностях',
    unit: 'м²',
    unitPrice: 90,
    source: 'pdf',
    kind: 'plaster',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-ceiling-main',
    title:
      'Оштукатуривание наклонных/потолочных поверхностей гипсовыми или клеевыми составами',
    unit: 'м²',
    unitPrice: 990,
    source: 'both',
    kind: 'plaster',
    frontendCategorySlug: 'shtukaturka',
    frontendName:
      'Оштукатуривание наклонных/потолочных поверхностей гипсовыми или клеевыми составами',
    frontendUnitPrice: 990,
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-ceiling-extra',
    title: 'Дополнительный слой штукатурки на наклонных/потолочных поверхностях свыше 40 мм',
    unit: 'м²',
    unitPrice: 325,
    source: 'pdf',
    kind: 'plaster',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },
  {
    id: 'plaster-ceiling-partial',
    title: 'Частичное выравнивание наклонных/потолочных поверхностей под правило',
    unit: 'м²',
    unitPrice: 455,
    source: 'pdf',
    kind: 'plaster',
    defaultEnabled: false,
    defaultQuantityFrom: 'plasterArea',
  },

  // —— Шпаклёвка / шлифовка ——
  {
    id: 'putty-ceiling-1',
    title: 'Шпаклевание потолка, 1 слой',
    unit: 'м²',
    unitPrice: 450,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Шпаклевание потолка, 1 слой',
    frontendUnitPrice: 450,
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-ceiling-2',
    title: 'Шпаклевание потолка, 2 слоя',
    unit: 'м²',
    unitPrice: 900,
    source: 'both',
    kind: 'putty',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Шпаклевание потолка, 2 слоя',
    frontendUnitPrice: 900,
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-finish-ceiling-1',
    title: 'Нанесение финишной шпаклевки на потолок, 1 слой',
    unit: 'м²',
    unitPrice: 450,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-finish-ceiling-2',
    title: 'Нанесение финишной шпаклевки на потолок, 2 слоя',
    unit: 'м²',
    unitPrice: 900,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-sanding-ceiling',
    title: 'Шлифовка потолка после шпаклевания',
    unit: 'м²',
    unitPrice: 300,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-finish-sanding-ceiling',
    title: 'Финишная шлифовка потолка',
    unit: 'м²',
    unitPrice: 420,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'putty-local-3mm',
    title: 'Локальное выравнивание поверхности шпаклевочной смесью до 3 мм',
    unit: 'м²',
    unitPrice: 380,
    source: 'pdf',
    kind: 'putty',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },

  // —— Армирование ——
  {
    id: 'reinforce-glassfiber-ceiling',
    title: 'Монтаж стеклохолста на потолок',
    unit: 'м²',
    unitPrice: 550,
    source: 'pdf',
    kind: 'reinforce',
    note: 'Labour only; материал холста не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'reinforce-paint-mesh',
    title: 'Монтаж малярной сетки в слой шпаклевки',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'reinforce',
    note: 'Labour only; материал сетки не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'puttyArea',
  },
  {
    id: 'finish-flizelin-ceiling',
    title: 'Оклейка потолка малярным флизелином (обои под покраску)',
    unit: 'м²',
    unitPrice: 950,
    source: 'pdf',
    kind: 'finish-paint',
    note: 'Labour only; флизелин как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'finishArea',
  },

  // —— Покраска ——
  {
    id: 'paint-ceiling-1',
    title: 'Покраска потолка валиком, 1 слой',
    unit: 'м²',
    unitPrice: 320,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Покраска потолка валиком, 1 слой',
    frontendUnitPrice: 320,
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'finishArea',
  },
  {
    id: 'paint-ceiling-2',
    title: 'Покраска потолка валиком, 2 слоя',
    unit: 'м²',
    unitPrice: 650,
    source: 'both',
    kind: 'finish-paint',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Покраска потолка валиком, 2 слоя',
    frontendUnitPrice: 650,
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'finishArea',
  },
  {
    id: 'paint-ceiling-3',
    title: 'Покраска потолка валиком, 3 слоя',
    unit: 'м²',
    unitPrice: 800,
    source: 'pdf',
    kind: 'finish-paint',
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'finishArea',
  },
  {
    id: 'paint-ceiling-mech-2',
    title: 'Механизированная покраска потолка, 2 слоя',
    unit: 'м²',
    unitPrice: 750,
    source: 'pdf',
    kind: 'finish-paint',
    note: 'Labour only; краска как материал не считаем',
    defaultEnabled: false,
    defaultQuantityFrom: 'finishArea',
  },
  {
    id: 'finish-check-light',
    title: 'Проверка поверхности под покраску проявочным светом',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'finish-paint',
    defaultEnabled: false,
    defaultQuantityFrom: 'finishArea',
  },
  {
    id: 'cover-protect',
    title: 'Укрытие плёнкой или бумагой пола, окон и дверей',
    unit: 'м²',
    unitPrice: 450,
    source: 'both',
    kind: 'prep',
    frontendCategorySlug: 'malyarnye',
    frontendName: 'Укрытие плёнкой или бумагой пола, окон и дверей',
    frontendUnitPrice: 450,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
]
