import type { Project } from './project.types'

// Temporary mock reviews; replace them with verified client feedback before publication.
export const projects: readonly Project[] = [
  {
    slug: '2-murinskiy-37',
    title: '2-й Муринский 37',
    type: 'Семейная квартира в старом фонде',
    typeAccent: 'в старом фонде',
    location: '2-й Муринский проспект 37',
    description: 'Восстановление сгоревшей квартиры в старом фонде: 59 кв. м',
    review: {
      quote:
        'После пожара квартира требовала полного восстановления, и нам было важно понимать каждый этап. Команда спокойно провела нас от демонтажа до готового интерьера и не потеряла ни одной важной детали.',
      details:
        'Особенно ценим, что сложные инженерные решения объясняли заранее, а сроки и бюджет обсуждались открыто. В итоге квартира снова стала удобным домом для всей семьи.',
      author: 'Марина и Алексей',
      projectInfo: 'Семейная квартира, 59 м²',
      location: 'Санкт-Петербург',
      rating: 5,
      service: 'Индивидуальный ремонт',
    },
    image: 'images/projects/2-murinskiy-37/36.webp',
    area: '59 м²',
    term: '8 месяцев',
    price: '3 000 000 ₽',
    size: 'tall',
    gallery: [
      'images/projects/2-murinskiy-37/01.webp',
      'images/projects/2-murinskiy-37/02.webp',
      'images/projects/2-murinskiy-37/03.webp',
      'images/projects/2-murinskiy-37/04.webp',
      'images/projects/2-murinskiy-37/05.webp',
      'images/projects/2-murinskiy-37/06.webp',
      'images/projects/2-murinskiy-37/07.webp',
      'images/projects/2-murinskiy-37/08.webp',
      'images/projects/2-murinskiy-37/09.webp',
      'images/projects/2-murinskiy-37/10.webp',
      'images/projects/2-murinskiy-37/11.webp',
      'images/projects/2-murinskiy-37/12.webp',
      'images/projects/2-murinskiy-37/13.webp',
      'images/projects/2-murinskiy-37/14.webp',
      'images/projects/2-murinskiy-37/15.webp',
      'images/projects/2-murinskiy-37/16.webp',
      'images/projects/2-murinskiy-37/17.webp',
      'images/projects/2-murinskiy-37/18.webp',
      'images/projects/2-murinskiy-37/19.webp',
      'images/projects/2-murinskiy-37/20.webp',
      'images/projects/2-murinskiy-37/21.webp',
      'images/projects/2-murinskiy-37/22.webp',
      'images/projects/2-murinskiy-37/23.webp',
      'images/projects/2-murinskiy-37/24.webp',
      'images/projects/2-murinskiy-37/25.webp',
      'images/projects/2-murinskiy-37/26.webp',
      'images/projects/2-murinskiy-37/27.webp',
      'images/projects/2-murinskiy-37/28.webp',
      'images/projects/2-murinskiy-37/29.webp',
      'images/projects/2-murinskiy-37/30.webp',
      'images/projects/2-murinskiy-37/31.webp',
      'images/projects/2-murinskiy-37/32.webp',
      'images/projects/2-murinskiy-37/33.webp',
      'images/projects/2-murinskiy-37/34.webp',
      'images/projects/2-murinskiy-37/35.webp',
      'images/projects/2-murinskiy-37/36.webp',
      'images/projects/2-murinskiy-37/37.webp',
      'images/projects/2-murinskiy-37/38.webp',
      'images/projects/2-murinskiy-37/39.webp',
    ],
    details: [
    'Наша команда успешно завершила масштабный проект по восстановлению квартиры площадью 59 кв. м, которая полностью сгорела. Заказчик приобрел это помещение и доверил нам его реконструкцию с нуля.',
    'Основные работы:',
    '1. Демонтаж и подготовка: Мы провели полный демонтаж оставшихся после пожара конструкций, чтобы подготовить помещение к новому этапу.',
    '2. Перегородки и пол : Были возведены новые перегородки из газобетона, выполнена стяжка пола и смонтирован наливной пол. В качестве чистового напольного покрытия выбран кварцвинил.',
    '3. Потолки и двери: Установлены натяжные потолки, которые придают помещению современный вид. Двери скрытого монтажа обеспечивают эстетичный и гармоничный интерьер.',
    '4. Отделка стен: Стены были тщательно подготовлены и окрашены, что создает ощущение свежести и уюта.',
    '5. Инженерные системы: Установлены бризеры для обеспечения свежего воздуха и комфортного микроклимата. Также были заменены окна на современные, энергоэффективные конструкции. В квартире создана гардеробная, где установлены сушильная и стиральная машины. Для отвода воды из стиральной машины в санузел установлен специальный насос SoloLift. В санузлах выполнена комбинированная отделка: нижняя часть стен облицована плиткой, а верхняя — окрашена. Установлена приточная вентиляция, которая обеспечивает циркуляцию воздуха во всей квартире, включая гардеробную, санузел и кухню. Вентиляторы скрыты, с ровными окрашенными примыканиями, что придает им эстетичный вид.',
    'Этот проект демонстрирует нашу способность справляться с самыми сложными задачами и превращать разрушенные помещения в комфортные и современные жилища. Мы гордимся тем, что смогли вернуть этой квартире вторую жизнь и предоставить заказчику качественное и функциональное пространство.',
  ],
  },
  {
    slug: 'zhk-grafika',
    title: 'ЖК Графика',
    type: 'Квартира-студия после перепланировки',
    typeAccent: 'после перепланировки',
    location: 'ЖК Графика',
    description: 'Преобразование студии в уютную однокомнатную квартиру в Мурино',
    review: {
      quote:
        'Из небольшой студии получилось полноценное пространство со спальней и удобным рабочим местом. Планировка стала намного логичнее, при этом квартира не выглядит тесной.',
      details:
        'Все решения по лоджии, раздвижной двери и умному свету согласовывали до начала работ. Было приятно видеть, как идеи превращаются в понятный и цельный интерьер.',
      author: 'Елена',
      projectInfo: 'Квартира-студия, 29,2 м²',
      location: 'Мурино',
      rating: 5,
      service: 'Индивидуальный ремонт',
    },
    image: 'images/projects/zhk-grafika/28.webp',
    area: '29,2 м²',
    term: '3 месяца',
    price: '1 200 000 ₽',
    size: 'wide',
    gallery: [
      'images/projects/zhk-grafika/01.webp',
      'images/projects/zhk-grafika/02.webp',
      'images/projects/zhk-grafika/03.webp',
      'images/projects/zhk-grafika/04.webp',
      'images/projects/zhk-grafika/05.webp',
      'images/projects/zhk-grafika/06.webp',
      'images/projects/zhk-grafika/07.webp',
      'images/projects/zhk-grafika/08.webp',
      'images/projects/zhk-grafika/09.webp',
      'images/projects/zhk-grafika/10.webp',
      'images/projects/zhk-grafika/11.webp',
      'images/projects/zhk-grafika/12.webp',
      'images/projects/zhk-grafika/13.webp',
      'images/projects/zhk-grafika/14.webp',
      'images/projects/zhk-grafika/15.webp',
      'images/projects/zhk-grafika/16.webp',
      'images/projects/zhk-grafika/17.webp',
      'images/projects/zhk-grafika/18.webp',
      'images/projects/zhk-grafika/19.webp',
      'images/projects/zhk-grafika/20.webp',
      'images/projects/zhk-grafika/21.webp',
      'images/projects/zhk-grafika/22.webp',
      'images/projects/zhk-grafika/23.webp',
      'images/projects/zhk-grafika/24.webp',
      'images/projects/zhk-grafika/25.webp',
      'images/projects/zhk-grafika/26.webp',
      'images/projects/zhk-grafika/27.webp',
      'images/projects/zhk-grafika/28.webp',
      'images/projects/zhk-grafika/29.webp',
      'images/projects/zhk-grafika/30.webp',
      'images/projects/zhk-grafika/31.webp',
      'images/projects/zhk-grafika/32.webp',
      'images/projects/zhk-grafika/33.webp',
      'images/projects/zhk-grafika/34.webp',
      'images/projects/zhk-grafika/35.webp',
      'images/projects/zhk-grafika/36.webp',
      'images/projects/zhk-grafika/37.webp',
      'images/projects/zhk-grafika/38.webp',
      'images/projects/zhk-grafika/39.webp',
    ],
    details: [
    'Наша команда успешно завершила проект по ремонту студии в Мурино, превратив ее в функциональную и комфортную однокомнатную квартиру.',
    'Основные работы:',
    'Создание отдельной спальни: Мы установили раздвижную дверь-купе (пенал), которая позволила эффективно использовать пространство и создать уютную спальню.',
    'Расширение жилого пространства: Был демонтирован балконный блок, а лоджия полностью утеплена с использованием Руспанели. Это позволило увеличить полезную площадь квартиры.',
    'Организация рабочего места: На утепленной лоджии было создано комфортное рабочее место, оборудованное теплым полом для дополнительного уюта.',
    'Интеграция умных технологий: В квартире установлен умный хаб Яндекс, а в выключателях — умные реле. Теперь с помощью голосового помощника Алисы можно регулировать освещение во всем помещении и управлять включением/отключением теплого пола.',
    'Полы и отделка: В зоне входа в квартиру уложена плитка, которая стыкуется с кварцвинилом в едином уровне, с герметичным примыканием. В ванной комнате вся поверхность облицована плиткой.',
    'Этот проект демонстрирует наш подход к максимальному использованию пространства и созданию комфортных условий для жизни. Мы рады, что смогли помочь нашим клиентам превратить их студию в уютную и функциональную однокомнатную квартиру с современными технологиями и качественными материалами.',
  ],
  },
  {
    slug: 'verkhnekamenskaya',
    title: 'Кофейня на Верхнекаменской',
    type: 'Коммерческое пространство в Приморском районе',
    typeAccent: 'в Приморском районе',
    location: 'ул. Верхнекаменская 11',
    description: 'Создание стильного пространства для кофейни и табачного магазина в Приморском районе.',
    review: {
      quote:
        'Нам было важно открыть кофейню к запланированной дате и получить пространство, удобное и для гостей, и для сотрудников. Команда выдержала темп и внимательно отнеслась к рабочим сценариям.',
      details:
        'Освещение, износостойкий пол и размещение оборудования продумали с учётом ежедневной нагрузки. После открытия интерьер остался таким же практичным, как мы и рассчитывали.',
      author: 'Ирина и Павел',
      projectInfo: 'Коммерческое помещение, 45 м²',
      location: 'Приморский район',
      rating: 4,
      service: 'Ремонт коммерческого помещения',
    },
    image: 'images/projects/verkhnekamenskaya/13.webp',
    area: '45 м²',
    term: '2 месяца',
    price: '1 200 000 ₽',
    size: 'standard',
    gallery: [
      'images/projects/verkhnekamenskaya/01.webp',
      'images/projects/verkhnekamenskaya/02.webp',
      'images/projects/verkhnekamenskaya/03.webp',
      'images/projects/verkhnekamenskaya/04.webp',
      'images/projects/verkhnekamenskaya/05.webp',
      'images/projects/verkhnekamenskaya/06.webp',
      'images/projects/verkhnekamenskaya/07.webp',
      'images/projects/verkhnekamenskaya/08.webp',
      'images/projects/verkhnekamenskaya/09.webp',
      'images/projects/verkhnekamenskaya/10.webp',
      'images/projects/verkhnekamenskaya/11.webp',
      'images/projects/verkhnekamenskaya/12.webp',
      'images/projects/verkhnekamenskaya/13.webp',
    ],
    details: [
    'Мы завершили интересный проект по ремонту кофейни-табачного магазина, расположенного на первом этаже жилого комплекса. В результате наших усилий появилось стильное и функциональное пространство, которое сочетает в себе уют кофейни и удобство табачного магазина.',
    'Основные работы:',
    'Дизайн и отделка: Стены были окрашены в теплые тона, создавая приятную атмосферу. Эпоксидный наливной пол добавляет современности и практичности.',
    'Освещение: Мы установили современное освещение, которое подчеркивает дизайн интерьера и создает комфортную обстановку для посетителей.',
    'Санузел: В санузле стены облицованы плиткой, что обеспечивает легкость ухода и эстетичный вид. Дверь скрытого монтажа добавляет изюминку в дизайн.',
    'Электрика: Полностью заменена электропроводка, что гарантирует безопасность и надежность работы всех систем.',
    'Сроки : Проект был выполнен всего за 2 месяца, что подчеркивает нашу способность работать быстро и качественно, не жертвуя при этом качеством работ.',
    'Этот проект демонстрирует наш подход к созданию стильных и функциональных пространств, которые привлекают посетителей и создают комфортную атмосферу. Мы рады, что смогли помочь нашим клиентам превратить их кофейню в привлекательное и современное место для отдыха и покупок.',
  ],
  },
  {
    slug: 'prospekt-slavy-4',
    title: 'пр. Славы 4',
    type: 'Квартира в старом фонде',
    typeAccent: 'в старом фонде',
    location: 'пр. Славы 4',
    description: 'Представьте себе уютную квартиру площадью 44 квадратных метра, где мы провели полный ремонт, превратив ее в современное и функциональное пространство.',
    review: {
      quote:
        'Квартира в старом фонде оказалась сложнее, чем мы ожидали, но процесс ремонта оставался понятным. Команда последовательно обновила основу и сохранила ощущение тёплого жилого пространства.',
      author: 'Ольга и Денис',
      projectInfo: 'Квартира в старом фонде, 44 м²',
      location: 'Санкт-Петербург',
      rating: 5,
      service: 'Индивидуальный ремонт',
    },
    image: 'images/projects/prospekt-slavy-4/22.webp',
    area: '44 м²',
    term: '6 месяцев',
    price: '1 500 000 ₽',
    size: 'standard',
    gallery: [
      'images/projects/prospekt-slavy-4/01.webp',
      'images/projects/prospekt-slavy-4/02.webp',
      'images/projects/prospekt-slavy-4/03.webp',
      'images/projects/prospekt-slavy-4/04.webp',
      'images/projects/prospekt-slavy-4/05.webp',
      'images/projects/prospekt-slavy-4/06.webp',
      'images/projects/prospekt-slavy-4/07.webp',
      'images/projects/prospekt-slavy-4/08.webp',
      'images/projects/prospekt-slavy-4/09.webp',
      'images/projects/prospekt-slavy-4/10.webp',
      'images/projects/prospekt-slavy-4/11.webp',
      'images/projects/prospekt-slavy-4/12.webp',
      'images/projects/prospekt-slavy-4/13.webp',
      'images/projects/prospekt-slavy-4/14.webp',
      'images/projects/prospekt-slavy-4/15.webp',
      'images/projects/prospekt-slavy-4/16.webp',
      'images/projects/prospekt-slavy-4/17.webp',
      'images/projects/prospekt-slavy-4/18.webp',
      'images/projects/prospekt-slavy-4/19.webp',
      'images/projects/prospekt-slavy-4/20.webp',
      'images/projects/prospekt-slavy-4/21.webp',
      'images/projects/prospekt-slavy-4/22.webp',
      'images/projects/prospekt-slavy-4/23.webp',
      'images/projects/prospekt-slavy-4/24.webp',
      'images/projects/prospekt-slavy-4/25.webp',
      'images/projects/prospekt-slavy-4/26.webp',
      'images/projects/prospekt-slavy-4/27.webp',
      'images/projects/prospekt-slavy-4/28.webp',
      'images/projects/prospekt-slavy-4/29.webp',
    ],
    details: [
    'Современный ремонт квартиры в старом фонде',
    'Какие работы были сделаны:',
    'Демонтаж и обновление: Мы полностью демонтировали старую стяжку во всей квартире и межкомнатные перегородки, чтобы создать прочное основание и просторное, функциональное пространство.',
    'Пол: На полу уложен ламинат, который придает помещению современный вид и создает ощущение уюта.',
    'Стены: Возведены новые перегородки из гипсокартона, потом оштукатурены и отшпаклеваны, далее оклеены обоями, которые добавляют стиль и индивидуальность, создавая атмосферу домашнего тепла.',
    'Санузел: В санузле уложена плитка, которая подчеркивает элегантность и функциональность пространства.',
    'Этот ремонт стал настоящим преображением, объединив современные решения и качественные материалы, чтобы создать уютный и стильный дом.',
  ],
  },
  {
    slug: 'forest-akvilon',
    title: 'ЖК Форест Аквилон на Планерной',
    type: 'Квартира для одного человека',
    typeAccent: 'для одного человека',
    location: 'ЖК Форест Аквилон на Планерной',
    description: 'Мы рады представить вам результат ремонта уютной однокомнатной квартиры площадью 38 квадратных метров, созданной специально для молодой девушки.',
    review: {
      quote:
        'Хотелось получить спокойную квартиру, где всё находится на своём месте и легко поддерживать порядок. Результат получился светлым, удобным и действительно подходящим для моего ритма жизни.',
      details:
        'Подбор материалов не растянулся на месяцы: варианты предлагали небольшими понятными подборками. Это заметно упростило решения и помогло удержать бюджет.',
      author: 'Алина',
      projectInfo: 'Однокомнатная квартира, 38 м²',
      location: 'Санкт-Петербург',
      rating: 5,
      service: 'Пакетный ремонт',
    },
    image: 'images/projects/forest-akvilon/01.webp',
    area: '38 м²',
    term: '5 месяцев',
    price: '1 100 000 ₽',
    size: 'wide',
    gallery: [
    'images/projects/forest-akvilon/01.webp',
    'images/projects/forest-akvilon/02.webp',
    'images/projects/forest-akvilon/03.webp',
    'images/projects/forest-akvilon/04.webp',
    'images/projects/forest-akvilon/05.webp',
    'images/projects/forest-akvilon/06.webp',
    'images/projects/forest-akvilon/07.webp',
    'images/projects/forest-akvilon/08.webp',
    'images/projects/forest-akvilon/09.webp',
    'images/projects/forest-akvilon/10.webp',
    'images/projects/forest-akvilon/11.webp',
    'images/projects/forest-akvilon/12.webp',
    'images/projects/forest-akvilon/13.webp',
    'images/projects/forest-akvilon/14.webp',
  ],
    details: [
    'В процессе работ были выполнены следующие задачи:',
    'Сантехнический узел: Ванная комната и туалет облицованы качественной плиткой, что обеспечивает стильный и практичный вид. – Пол: В качестве напольного покрытия выбран кварцвинил, который отличается прочностью и привлекательным внешним видом. – Стены: Стены окрашены в разные цвета, при этом особое внимание уделено аккуратному и красивому стыку двух цветов, что придает интерьеру индивидуальность и стиль. – Потолок: Установлен натяжной потолок, который добавляет пространству легкости и завершенности.',
    'Этот ремонт выполнен в современном стиле, с учетом всех пожеланий заказчика. Мы уверены, что эта квартира станет уютным и комфортным местом для жизни.',
  ],
  },
  {
    slug: 'id-kudrovo',
    title: 'ЖК iD Kudrovo',
    type: 'Функциональная квартира для одного человека',
    typeAccent: 'для одного человека',
    location: 'ЖК iD Kudrovo',
    description: 'Современный и функциональный ремонт однокомнатной квартиры для молодого жителя мегаполиса.',
    review: {
      quote:
        'В небольшой квартире удалось разместить всё необходимое без ощущения перегруженности. Мне понравилось, что команда предлагала практичные решения и сразу объясняла их влияние на стоимость.',
      details:
        'Отдельно отмечу аккуратную стыковку покрытий и удобную кухонную зону. В повседневной жизни эти детали оказались действительно важными.',
      author: 'Михаил',
      projectInfo: 'Однокомнатная квартира, 35 м²',
      rating: 4,
      service: 'Пакетный ремонт',
    },
    image: 'images/projects/id-kudrovo/01.webp',
    area: '35 м²',
    term: '3 месяца',
    price: '940 000 ₽',
    size: 'standard',
    gallery: [
      'images/projects/id-kudrovo/01.webp',
      'images/projects/id-kudrovo/02.webp',
      'images/projects/id-kudrovo/03.webp',
      'images/projects/id-kudrovo/04.webp',
      'images/projects/id-kudrovo/05.webp',
      'images/projects/id-kudrovo/06.webp',
      'images/projects/id-kudrovo/07.webp',
      'images/projects/id-kudrovo/08.webp',
      'images/projects/id-kudrovo/09.webp',
      'images/projects/id-kudrovo/10.webp',
      'images/projects/id-kudrovo/11.webp',
      'images/projects/id-kudrovo/12.webp',
      'images/projects/id-kudrovo/13.webp',
      'images/projects/id-kudrovo/14.webp',
      'images/projects/id-kudrovo/15.webp',
    ],
    details: [
    'Наш клиент, молодой человек около 30 лет, обратился к нам с запросом на создание уютного и практичного пространства в своей однокомнатной квартире. Основной акцент был сделан на функциональность и экономичность, чтобы создать комфортное жилье без лишних затрат.',
    'Основные работы:',
    'Ванная комната: Вместо традиционной ванны была установлена душевая кабина с поддоном, облицованным плиткой. Это решение позволило сэкономить пространство и сделать ванную более современной и удобной. – Стены: По желанию клиента, стены были оклеены обоями. Это доступный и популярный вариант отделки, который позволяет легко обновлять интерьер при необходимости. – Пол: В спальне и гостиной был уложен ламинат, который отличается прочностью и простотой в уходе. В зоне кухни, отделенной от гостиной, пол был выложен плиткой, что обеспечивает практичность и легкость в уборке.',
    'Этот ремонт стал отличным примером того, как можно создать комфортное и стильное жилье, учитывая бюджет и пожелания клиента. Мы гордимся результатом и рады, что смогли помочь нашему клиенту создать дом своей мечты!',
  ],
  },
  {
    slug: 'grand-house',
    title: 'ЖК Гранд Хаус на Миргородской',
    type: 'Квартира для современного ритма жизни',
    typeAccent: 'для современного ритма жизни',
    location: 'ЖК Гранд Хаус на Миргородской',
    description: 'Мы рады представить вам результат нашего труда — полностью обновленную квартиру с акцентом на комфорт, стиль и спокойную эстетику. Изначально помещение было пустым: отсутствовали перегородки, стяжка, электрика и другие необходимые элементы. Мы начали работу с нуля, создавая уютное пространство с учетом всех пожеланий заказчика.',
    review: {
      quote:
        'Работы начинались в совершенно пустой квартире, поэтому особенно важно было заранее увидеть логику будущего пространства. Команда выстроила процесс по этапам, и результат полностью совпал с нашими ожиданиями.',
      details:
        'Планировка, электрика и отделка воспринимаются как единое целое. Мы получали регулярные обновления и могли принимать решения без спешки и лишней неопределённости.',
      author: 'Наталья',
      projectInfo: 'Квартира, 46 м²',
      location: 'Санкт-Петербург',
      rating: 5,
    },
    image: 'images/projects/grand-house/05.webp',
    area: '46 м²',
    term: '4 месяца',
    price: '920 000 ₽',
    size: 'tall',
    gallery: [
      'images/projects/grand-house/01.webp',
      'images/projects/grand-house/02.webp',
      'images/projects/grand-house/03.webp',
      'images/projects/grand-house/04.webp',
      'images/projects/grand-house/05.webp',
      'images/projects/grand-house/06.webp',
      'images/projects/grand-house/07.webp',
      'images/projects/grand-house/08.webp',
      'images/projects/grand-house/09.webp',
      'images/projects/grand-house/10.webp',
      'images/projects/grand-house/11.webp',
      'images/projects/grand-house/12.webp',
      'images/projects/grand-house/13.webp',
      'images/projects/grand-house/14.webp',
      'images/projects/grand-house/15.webp',
    ],
    details: [
    'В процессе ремонта были выполнены следующие работы:',
    'Возвездение перегородок : Мы установили новые перегородки из газобетона, чтобы разделить пространство на функциональные зоны. – Стяжка пола: Пол был выровнен и подготовлен для укладки финишного покрытия. – Электрика: Проведены все необходимые работы по электрике, установлены розетки и выключатели. – Штукатурка стен: Стены были тщательно оштукатурены и подготовлены к поклейке обоев. – Потолок: Потолок был выровнен и покрашен, что придает помещению аккуратный и завершенный вид.',
    'В качестве финишного покрытия пола был выбран кварцвинил, который отличается прочностью и эстетичным внешним видом. Стены оклеены обоями, что позволяет создать уютную и теплую атмосферу. Потолок, окрашенный в нейтральный цвет, гармонично дополняет интерьер.',
    'Мы гордимся результатом нашей работы и уверены, что эта квартира станет уютным домом для своей владелицы.',
  ],
  },
] as const
