import type { FloorPriceMappingItem } from '../shared/estimate.types'

/**
 * Explicit whitelist of rough-floor works for internal estimate MVP.
 *
 * Primary source: PDF `anfas-price-list.pdf` (2026-07-29).
 * Frontend `prices.data.ts` used only for verification when `source` is `both`.
 * Finish coverings (laminate/quartz/parquet install) are intentionally excluded.
 */
export const FLOOR_PRICE_MAPPING: readonly FloorPriceMappingItem[] = [
  // —— Демонтаж ——
  {
    id: 'demolition-plinth',
    title: 'Демонтаж плинтуса',
    unit: 'м. пог.',
    unitPrice: 120,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж плинтуса',
    frontendUnitPrice: 120,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'demolition-laminate',
    title: 'Демонтаж ламината',
    unit: 'м²',
    unitPrice: 300,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж ламината',
    frontendUnitPrice: 300,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-floating-laminate-engineered',
    title: 'Демонтаж покрытия из ламината и инженерной доски собранных по плавающему типу',
    unit: 'м²',
    unitPrice: 360,
    source: 'pdf',
    kind: 'demolition',
    note: 'PDF-only; не путать с базовым «Демонтаж ламината» 300 ₽',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-linoleum',
    title: 'Демонтаж линолеума',
    unit: 'м²',
    unitPrice: 200,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж линолеума',
    frontendUnitPrice: 200,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-parquet-board',
    title: 'Демонтаж паркетной доски',
    unit: 'м²',
    unitPrice: 500,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-glued-parquet',
    title: 'Демонтаж паркета приклеенного к основанию',
    unit: 'м²',
    unitPrice: 750,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-wooden-floors',
    title: 'Демонтаж деревянных полов',
    unit: 'м²',
    unitPrice: 550,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-rough-boards',
    title: 'Демонтаж черновых досок (полов)',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-glue-underlay',
    title: 'Демонтаж клея/подложки',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-floor-battens',
    title: 'Демонтаж обрешетки пола',
    unit: 'м²',
    unitPrice: 300,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-joists',
    title: 'Демонтаж лаг',
    unit: 'м²',
    unitPrice: 500,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-fill-to-100',
    title: 'Демонтаж засыпки-мусора до 100 мм',
    unit: 'м²',
    unitPrice: 650,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-screed-up-to-70',
    title: 'Демонтаж стяжки до 70 мм',
    unit: 'м²',
    unitPrice: 1100,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж стяжки до 70 мм',
    frontendUnitPrice: 1100,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-screed-over-70',
    title: 'Демонтаж стяжки более 70 мм',
    unit: 'м²',
    unitPrice: 1300,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-floor-tile',
    title: 'Демонтаж плитки пола',
    unit: 'м²',
    unitPrice: 900,
    source: 'both',
    kind: 'demolition',
    frontendCategorySlug: 'demontazh',
    frontendName: 'Демонтаж плитки пола',
    frontendUnitPrice: 900,
    defaultEnabled: false,
    defaultQuantityFrom: 'demolitionArea',
  },
  {
    id: 'demolition-damper-sound-after-screed',
    title:
      'Подрезка/демонтаж демпферных лент и напольной звукоизоляции после монтажа стяжки, отработка примыканий стяжки и деформационных швов полиуретановым герметиком',
    unit: 'м²',
    unitPrice: 160,
    source: 'pdf',
    kind: 'demolition',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },

  // —— Общая подготовка / грунт ——
  {
    id: 'base-dust-removal-general',
    title: 'Обеспыливание основания перед общестроительными работами',
    unit: 'м²',
    unitPrice: 80,
    source: 'pdf',
    kind: 'base-prep',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'primer-deep-penetration',
    title: 'Грунтование основания грунтовкой глубокого проникновения',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'primer-betonkontakt',
    title: 'Нанесение бетонконтакта на бетонные поверхности',
    unit: 'м²',
    unitPrice: 180,
    source: 'pdf',
    kind: 'primer',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },

  // —— Полусухая стяжка ——
  {
    id: 'semidry-prep',
    title: 'Подготовка основания под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 300,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-dust-removal',
    title: 'Обеспыливание основания под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 80,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-primer',
    title: 'Грунтование основания под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-expanded-clay',
    title: 'Заполнение пола керамзитом под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 450,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-pe-film',
    title: 'Монтаж полиэтиленовой пленки под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 200,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-sound-layer',
    title: 'Укладка шумоизоляционного слоя под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 300,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-damper-tape',
    title: 'Монтаж демпферной ленты по периметру полусухой стяжки',
    unit: 'м. пог.',
    unitPrice: 150,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'semidry-beacons',
    title: 'Установка маяков под устройство полусухой стяжки',
    unit: 'м²',
    unitPrice: 200,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-mesh',
    title: 'Армирование полусухой стяжки металлической сеткой',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-mix-distribution',
    title: 'Приём и распределение готовой смеси при устройстве полусухой стяжки',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-screed-up-to-80',
    title: 'Устройство полусухой стяжки пола толщиной до 80 мм',
    unit: 'м²',
    unitPrice: 1300,
    source: 'both',
    kind: 'screed-semidry',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Устройство полусухой стяжки пола толщиной до 80 мм',
    frontendUnitPrice: 1300,
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-screed-over-80',
    title: 'Устройство полусухой стяжки пола толщиной свыше 80 мм',
    unit: 'м²',
    unitPrice: 1600,
    source: 'both',
    kind: 'screed-semidry',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Устройство полусухой стяжки пола толщиной свыше 80 мм',
    frontendUnitPrice: 1600,
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-cover-pe',
    title: 'Укрывка полусухой стяжки полиэтиленом',
    unit: 'м²',
    unitPrice: 80,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-curing',
    title: 'Смачивание полусухой стяжки водой и уход за стяжкой',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'semidry-damper-rope',
    title: 'Монтаж жгута в демпферный шов полусухой стяжки',
    unit: 'м. пог.',
    unitPrice: 200,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'semidry-damper-seal',
    title: 'Герметизация демпферного шва полусухой стяжки',
    unit: 'м. пог.',
    unitPrice: 350,
    source: 'pdf',
    kind: 'screed-semidry',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },

  // —— Мокрая стяжка ——
  {
    id: 'wet-prep',
    title: 'Подготовка основания под устройство мокрой стяжки',
    unit: 'м²',
    unitPrice: 350,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-grind',
    title: 'Шлифование и зачистка основания под устройство мокрой стяжки',
    unit: 'м²',
    unitPrice: 450,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-dust-removal',
    title: 'Обеспыливание основания под устройство мокрой стяжки',
    unit: 'м²',
    unitPrice: 100,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-primer',
    title: 'Грунтование основания под устройство мокрой стяжки',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-pe-film',
    title: 'Монтаж полиэтиленовой пленки под устройство мокрой стяжки',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-damper-tape',
    title: 'Монтаж демпферной ленты по периметру мокрой стяжки',
    unit: 'м. пог.',
    unitPrice: 200,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'wet-beacons',
    title: 'Установка маяков под устройство мокрой стяжки',
    unit: 'м²',
    unitPrice: 300,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-mesh',
    title: 'Армирование мокрой стяжки металлической сеткой',
    unit: 'м²',
    unitPrice: 450,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-hand-mix',
    title: 'Ручное замешивание раствора для устройства мокрой стяжки',
    unit: 'м²',
    unitPrice: 600,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-screed-up-to-50',
    title: 'Устройство мокрой стяжки пола толщиной до 50 мм ручным способом',
    unit: 'м²',
    unitPrice: 1800,
    source: 'both',
    kind: 'screed-wet',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Устройство мокрой стяжки пола толщиной до 50 мм ручным способом',
    frontendUnitPrice: 1800,
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-screed-50-to-80',
    title: 'Устройство мокрой стяжки пола толщиной 50–80 мм ручным способом',
    unit: 'м²',
    unitPrice: 2200,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-screed-over-80',
    title: 'Устройство мокрой стяжки пола толщиной свыше 80 мм ручным способом',
    unit: 'м²',
    unitPrice: 2600,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-screed-local-small',
    title: 'Устройство локального участка мокрой стяжки при малом объёме работ',
    unit: 'м²',
    unitPrice: 2800,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'wet-cover-pe',
    title: 'Укрывка мокрой стяжки полиэтиленом',
    unit: 'м²',
    unitPrice: 100,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-curing',
    title: 'Смачивание мокрой стяжки водой и уход за мокрой стяжкой',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'wet-damper-seal',
    title: 'Герметизация демпферного шва мокрой стяжки',
    unit: 'м. пог.',
    unitPrice: 450,
    source: 'pdf',
    kind: 'screed-wet',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },

  // —— Наливной пол ——
  {
    id: 'self-leveling-prep',
    title: 'Подготовка бетонного пола к устройству наливного пола',
    unit: 'м²',
    unitPrice: 150,
    source: 'pdf',
    kind: 'self-leveling',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'self-leveling-grind',
    title: 'Шлифование бетонного пола перед устройством наливного пола',
    unit: 'м²',
    unitPrice: 250,
    source: 'pdf',
    kind: 'self-leveling',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'self-leveling-dust-removal',
    title: 'Обеспыливание бетонного пола перед устройством наливного пола',
    unit: 'м²',
    unitPrice: 80,
    source: 'pdf',
    kind: 'self-leveling',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'self-leveling-primer',
    title: 'Грунтование бетонного пола перед устройством наливного пола',
    unit: 'м²',
    unitPrice: 120,
    source: 'pdf',
    kind: 'self-leveling',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'self-leveling-beacons',
    title: 'Монтаж маяков для устройства наливного пола',
    unit: 'м²',
    unitPrice: 200,
    source: 'pdf',
    kind: 'self-leveling',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'self-leveling-device',
    title: 'Устройство наливного пола',
    unit: 'м²',
    unitPrice: 900,
    source: 'both',
    kind: 'self-leveling',
    frontendCategorySlug: 'obshhestroitelnye',
    frontendName: 'Устройство наливного пола',
    frontendUnitPrice: 900,
    note: 'В прайсе нет отдельной позиции «ровнитель» — используется «наливной пол»',
    defaultEnabled: false,
    defaultQuantityFrom: 'screedArea',
  },
  {
    id: 'self-leveling-local-small',
    title: 'Устройство локального участка наливного пола при малом объёме работ',
    unit: 'м²',
    unitPrice: 1600,
    source: 'pdf',
    kind: 'self-leveling',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },

  // —— Гидроизоляция мокрых зон ——
  {
    id: 'waterproofing-acrylic-1',
    title: 'Нанесение гидроизоляции на акриловой основе, 1 слой',
    unit: 'м²',
    unitPrice: 350,
    source: 'both',
    kind: 'waterproofing',
    frontendCategorySlug: 'plitka',
    frontendName: 'Нанесение гидроизоляции на акриловой основе, 1 слой',
    frontendUnitPrice: 350,
    defaultEnabled: false,
    defaultQuantityFrom: 'wetZonesArea',
  },
  {
    id: 'waterproofing-acrylic-2',
    title: 'Нанесение гидроизоляции на акриловой основе, 2 слоя',
    unit: 'м²',
    unitPrice: 700,
    source: 'both',
    kind: 'waterproofing',
    frontendCategorySlug: 'plitka',
    frontendName: 'Нанесение гидроизоляции на акриловой основе, 2 слоя',
    frontendUnitPrice: 700,
    defaultEnabled: false,
    defaultQuantityFrom: 'wetZonesArea',
  },
  {
    id: 'waterproofing-cement-2',
    title: 'Нанесение цементной гидроизоляции в 2 слоя',
    unit: 'м²',
    unitPrice: 850,
    source: 'pdf',
    kind: 'waterproofing',
    defaultEnabled: false,
    defaultQuantityFrom: 'wetZonesArea',
  },
  {
    id: 'waterproofing-shower-tray',
    title: 'Гидроизоляция душевого поддона перед облицовкой плиткой',
    unit: 'м²',
    unitPrice: 900,
    source: 'pdf',
    kind: 'waterproofing',
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },

  // —— Вывоз мусора (optional, never auto-enabled) ——
  {
    id: 'waste-pass-permit',
    title: 'Организация пропуска для машины/ПУХТО на территорию ЖК',
    unit: 'комплекс',
    unitPrice: 1000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Организация пропуска для машины/ПУХТО на территорию ЖК',
    frontendUnitPrice: 1000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-gazelle-6',
    title: 'Вывоз строительного мусора Газелью до 6 м³',
    unit: 'рейс',
    unitPrice: 8000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Вывоз строительного мусора Газелью до 6 м³',
    frontendUnitPrice: 8000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-gazelle-12',
    title: 'Вывоз строительного мусора Газелью до 12 м³',
    unit: 'рейс',
    unitPrice: 13000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Вывоз строительного мусора Газелью до 12 м³',
    frontendUnitPrice: 13000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-gazelle-16',
    title: 'Вывоз строительного мусора Газелью до 16 м³',
    unit: 'рейс',
    unitPrice: 16000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Вывоз строительного мусора Газелью до 16 м³',
    frontendUnitPrice: 16000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-puhto-20',
    title: 'Подача и вывоз ПУХТО 20 м³ для строительного мусора',
    unit: 'рейс',
    unitPrice: 28000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Подача и вывоз ПУХТО 20 м³ для строительного мусора',
    frontendUnitPrice: 28000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-puhto-27',
    title: 'Подача и вывоз ПУХТО 27 м³ для строительного мусора',
    unit: 'рейс',
    unitPrice: 33000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Подача и вывоз ПУХТО 27 м³ для строительного мусора',
    frontendUnitPrice: 33000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-manual-load',
    title: 'Ручная погрузка строительного мусора грузчиками в Газель/ПУХТО',
    unit: 'м³',
    unitPrice: 1200,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Ручная погрузка строительного мусора грузчиками в Газель/ПУХТО',
    frontendUnitPrice: 1200,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-carry-out',
    title: 'Вынос строительного мусора пешком/через лифт с привлечением местного исполнителя',
    unit: 'м³',
    unitPrice: 1500,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Вынос строительного мусора пешком/через лифт с привлечением местного исполнителя',
    frontendUnitPrice: 1500,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
  {
    id: 'waste-heavy-surcharge',
    title: 'Доплата за крупногабаритный или тяжёлый строительный мусор',
    unit: 'комплекс',
    unitPrice: 3000,
    source: 'both',
    kind: 'waste',
    frontendCategorySlug: 'vyvoz-musora',
    frontendName: 'Доплата за крупногабаритный или тяжёлый строительный мусор',
    frontendUnitPrice: 3000,
    defaultEnabled: false,
    defaultQuantityFrom: 'manual',
  },
] as const

export const FLOOR_SECTION_ID = 'floors'
export const FLOOR_SECTION_TITLE = 'Полы (черновые работы)'
